import bpy, bmesh, math, os
from mathutils import Vector
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..')) if '__file__' in globals() else os.getcwd(); OUT=os.path.join(ROOT,'output')
scene=bpy.context.scene

# Load baseline generated by build_model.py, then rebuild only the parts where
# silhouette/camera/material matching matters most. This preserves the good porch,
# fence and landscaping work while correcting the roof/dormer/camera mismatch.

def mat_obj(name): return bpy.data.materials.get(name)
W=mat_obj('Wall_Main'); T=mat_obj('Trim_White'); RB=mat_obj('Roof_Blue'); RT=mat_obj('Roof_Tile'); WD=mat_obj('Wood'); WL=mat_obj('Wood_Light'); BR=mat_obj('Brick'); BL=mat_obj('Brick_Light'); BG=mat_obj('Backdrop')

def set_base(m,c,rough=None):
    if not m:return
    m.diffuse_color=(*c,1); m.use_nodes=True; p=m.node_tree.nodes.get('Principled BSDF')
    if p:
        p.inputs['Base Color'].default_value=(*c,1)
        if rough is not None:p.inputs['Roughness'].default_value=rough
# Reference-measured palette (linearized/visually compensated for studio light)
set_base(W,(0.945,0.89,0.80),.82); set_base(T,(0.985,0.975,0.94),.74)
set_base(RB,(0.032,0.115,0.285),.66); set_base(RT,(0.040,0.145,0.345),.64)
set_base(WD,(0.33,0.13,0.035),.72); set_base(WL,(0.57,0.26,0.065),.70)
set_base(BR,(0.64,0.31,0.095),.80); set_base(BL,(0.83,0.50,0.19),.80)
set_base(BG,(0.985,0.955,0.885),.96)

def assign(o,m):
    o.data.materials.clear(); o.data.materials.append(m)
def bevel(o,w=.008):
    if w<=0:return
    md=o.modifiers.new('ExpertBevel','BEVEL'); md.width=w; md.segments=2; md.limit_method='ANGLE'; bpy.context.view_layer.objects.active=o; bpy.ops.object.modifier_apply(modifier=md.name)
def box(n,loc,dims,m,bev=.008,rot=(0,0,0)):
    bpy.ops.mesh.primitive_cube_add(size=1,location=loc,rotation=rot); o=bpy.context.object; o.name=n; o.dimensions=dims; bpy.ops.object.transform_apply(location=False,rotation=False,scale=True); assign(o,m); bevel(o,bev); return o
def mesh(n,v,f,m):
    me=bpy.data.meshes.new(n+'_Mesh'); me.from_pydata(v,[],f); me.validate(); me.update(); o=bpy.data.objects.new(n,me); bpy.context.collection.objects.link(o); assign(o,m); return o
def tri_prism(n,x0,x1,z0,z1,y0,y1,m):
    xc=(x0+x1)/2; v=[(x0,y0,z0),(x1,y0,z0),(xc,y0,z1),(x0,y1,z0),(x1,y1,z0),(xc,y1,z1)]; f=[(0,1,2),(3,5,4),(0,3,4,1),(1,4,5,2),(2,5,3,0)]; return mesh(n,v,f,m)
def slope_x(n,xe,xr,yc,yd,ze,zr,m,th=.085):
    p0=Vector((xe,yc,ze));p1=Vector((xr,yc,zr));d=p1-p0;a=math.atan2(d.z,d.x);return box(n,(p0+p1)/2,(d.length,yd,th),m,.006,(0,-a,0))
def slope_y(n,ye,yr,xc,xd,ze,zr,m,th=.085):
    p0=Vector((xc,ye,ze));p1=Vector((xc,yr,zr));d=p1-p0;a=math.atan2(d.z,d.y);return box(n,(p0+p1)/2,(xd,d.length,th),m,.006,(a,0,0))
def beam(n,p0,p1,t,m,d=None):
    p0=Vector(p0);p1=Vector(p1);v=p1-p0;bpy.ops.mesh.primitive_cube_add(size=1,location=(p0+p1)/2);o=bpy.context.object;o.name=n;o.dimensions=(v.length,t,d or t);o.rotation_mode='QUATERNION';o.rotation_quaternion=v.to_track_quat('X','Z');bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);assign(o,m);bevel(o,min(.008,t*.2));return o

def tiles_y(pre,ye,yr,xc,xd,ze,zr,rows,cols):
    p0=Vector((xc,ye,ze));p1=Vector((xc,yr,zr));d=p1-p0;L=d.length;u=d.normalized();a=math.atan2(d.z,d.y);rl=L/rows*.94;cw=xd/cols*.94
    for r in range(rows):
        s=(r+.47)*L/rows; st=.48*cw if r%2 else 0
        for c in range(cols+1):
            x=xc-xd/2+(c+.5)*xd/cols+st
            if x>xc+xd/2-cw*.2:continue
            p=p0+u*s; box(f'{pre}_{r}_{c}',(x,p.y,p.z+.04),(cw,rl,.022),RT,.002,(a,0,0))
def tiles_x(pre,xe,xr,yc,yd,ze,zr,rows,cols):
    p0=Vector((xe,yc,ze));p1=Vector((xr,yc,zr));d=p1-p0;L=d.length;u=d.normalized();a=math.atan2(d.z,d.x);rl=L/rows*.94;cw=yd/cols*.94
    for r in range(rows):
        s=(r+.47)*L/rows; st=.48*cw if r%2 else 0
        for c in range(cols+1):
            y=yc-yd/2+(c+.5)*yd/cols+st
            if y>yc+yd/2-cw*.2:continue
            p=p0+u*s; box(f'{pre}_{r}_{c}',(p.x,y,p.z+.04),(rl,cw,.022),RT,.002,(0,-a,0))

def remove_prefixes(prefixes):
    for o in list(bpy.data.objects):
        if any(o.name.startswith(p) for p in prefixes): bpy.data.objects.remove(o,do_unlink=True)

# Delete the old chunky/misproportioned roof and dormer only.
remove_prefixes(['RoofMain','TileMain','RoofCross','TileCross','Dormer','TileCross','Chimney','PorchRoof','PorchTile','EntryRoof','EntryTile','EntryRidge'])

# Main roof: hipped on the visible right end. The reference does not expose a huge
# white triangular gable here; the blue roof wraps down around the dormer.
xMin=-2.55; xMax=2.15; ridgeMin=-2.10; ridgeMax=1.23; yr=.48; yF=-2.10; yB=2.40; zE=3.30; zR=5.24
def solid_poly(name,pts,mat,th=.075):
    me=bpy.data.meshes.new(name+'_Mesh'); me.from_pydata(pts,[],[tuple(range(len(pts)))]); me.update(); o=bpy.data.objects.new(name,me); bpy.context.collection.objects.link(o); assign(o,mat)
    bpy.context.view_layer.objects.active=o; o.select_set(True); md=o.modifiers.new('Solidify','SOLIDIFY'); md.thickness=th; md.offset=0; bpy.ops.object.modifier_apply(modifier=md.name); o.select_set(False); return o
solid_poly('Expert_Main_F',[(xMin,yF,zE),(xMax,yF,zE),(ridgeMax,yr,zR),(ridgeMin,yr,zR)],RB)
solid_poly('Expert_Main_B',[(xMin,yB,zE),(ridgeMin,yr,zR),(ridgeMax,yr,zR),(xMax,yB,zE)],RB)
solid_poly('Expert_Main_Hip_R',[(xMax,yF,zE),(xMax,yB,zE),(ridgeMax,yr,zR)],RB)
solid_poly('Expert_Main_Hip_L',[(xMin,yB,zE),(xMin,yF,zE),(ridgeMin,yr,zR)],RB)
box('Expert_Main_Ridge',((ridgeMin+ridgeMax)/2,yr,zR+.055),(ridgeMax-ridgeMin+.16,.15,.15),RT,.04)
# Trapezoid-clipped shingle tiles on the two large roof slopes.
def main_slope_tiles(prefix,front=True,rows=8,cols=12):
    y0=yF if front else yB; d=Vector((0,yr-y0,zR-zE)); L=d.length; u=d.normalized(); a=math.atan2(d.z,d.y)
    for r in range(rows):
        t=(r+.48)/rows; p=Vector((0,y0,zE))+u*(t*L); xl=xMin+(ridgeMin-xMin)*t; xr_=xMax+(ridgeMax-xMax)*t; span=xr_-xl; cw=span/cols*.92; rl=L/rows*.91
        for c in range(cols):
            st=(.46*span/cols if r%2 else 0); x=xl+(c+.5)*span/cols+st
            if x>xr_-cw*.2: continue
            box(f'{prefix}_{r}_{c}',(x,p.y,p.z+.04),(cw,rl,.022),RT,.002,(a,0,0))
main_slope_tiles('ExpertTileMF',True); main_slope_tiles('ExpertTileMB',False)
# Raised shingle rows on the visible right hip.
for i,t in enumerate([.14,.27,.40,.53,.66,.79,.90]):
    x=xMax+(ridgeMax-xMax)*t; z=zE+(zR-zE)*t; ya=yF+(yr-yF)*t; yb=yB+(yr-yB)*t; L=yb-ya
    box(f'ExpertHipRow_{i}',(x,(ya+yb)/2,z+.045),(.030,L,.022),RT,.002)
# Cross-gable is CLIPPED at the roof valley instead of using two full rectangular
# planes. The previous rectangles continued behind the valley and created the huge
# triangular sheet seen in V5.
xr=-1.15; xL=-2.72; xR=.42; zEg=3.28; zRg=5.20; gfront=-2.14
sm=(zR-zE)/(yr-yF); ridge_valley_y=yF+(zRg-zE)/sm
def solid_tri(name,pts,mat,th=.075):
    me=bpy.data.meshes.new(name+'_Mesh'); me.from_pydata(pts,[],[(0,1,2)]); me.update(); o=bpy.data.objects.new(name,me); bpy.context.collection.objects.link(o); assign(o,mat)
    bpy.context.view_layer.objects.active=o; o.select_set(True); md=o.modifiers.new('Solidify','SOLIDIFY'); md.thickness=th; md.offset=0; bpy.ops.object.modifier_apply(modifier=md.name); o.select_set(False); return o
solid_tri('Expert_Gable_L',[(xL,gfront,zEg),(xr,gfront,zRg),(xr,ridge_valley_y,zRg)],RB)
solid_tri('Expert_Gable_R',[(xR,gfront,zEg),(xr,gfront,zRg),(xr,ridge_valley_y,zRg)],RB)
# Thin shingle row lines follow the clipped triangular roof, avoiding floating tiles.
def gable_rows(prefix,eave_x):
    for i,t in enumerate([.13,.25,.37,.49,.61,.73,.85,.95]):
        x=eave_x+(xr-eave_x)*t; z=zEg+(zRg-zEg)*t; ymax=yF+(z-zE)/sm; L=max(.06,ymax-gfront)
        box(f'{prefix}_{i}',(x,gfront+L/2,z+.048),(.030,L,.022),RT,.002)
gable_rows('ExpertGableRowL',xL); gable_rows('ExpertGableRowR',xR)
# Ridge stops exactly at the valley.
rlen=ridge_valley_y-gfront; box('Expert_Gable_Ridge',(xr,gfront+rlen/2,zRg+.055),(.15,rlen,.15),RT,.04)
beam('Expert_Fascia_L',(-2.44,-2.01,3.30),(-1.15,-2.01,5.02),.07,T,.075); beam('Expert_Fascia_R',(-1.15,-2.01,5.02),(.16,-2.01,3.30),.07,T,.075)

# Right dormer: wider, lower and more integrated into the roof.
box('Expert_Dormer_Body',(.92,-.73,4.08),(1.30,1.05,1.08),W,.014); tri_prism('Expert_Dormer_Gable',.27,1.57,4.50,5.06,-1.275,-1.16,W)
slope_x('Expert_Dormer_RL',.15,.92,-.72,1.38,4.48,5.12,RB); slope_x('Expert_Dormer_RR',1.69,.92,-.72,1.38,4.48,5.12,RB)
tiles_x('ExpertDormerTL',.15,.92,-.72,1.38,4.48,5.12,5,5); tiles_x('ExpertDormerTR',1.69,.92,-.72,1.38,4.48,5.12,5,5); box('Expert_Dormer_Ridge',(.92,-.72,5.17),(.14,1.45,.14),RT,.035)
# reuse a compact manually-built window on dormer face
box('Expert_Dormer_Frame',(.92,-1.30,4.22),(.75,.09,.80),T,.008); box('Expert_Dormer_Glass',(.92,-1.355,4.22),(.56,.025,.60),bpy.data.materials.get('Glass'),.002); box('Expert_Dormer_V',(.92,-1.37,4.22),(.04,.025,.60),T,.002); box('Expert_Dormer_H',(.92,-1.37,4.22),(.56,.025,.04),T,.002)
beam('Expert_Dormer_Fascia_L',(.27,-1.30,4.50),(.92,-1.30,5.06),.052,T,.055); beam('Expert_Dormer_Fascia_R',(.92,-1.30,5.06),(1.57,-1.30,4.50),.052,T,.055)

# Chimney farther back/right and slightly taller.
box('Expert_Chimney',(1.38,1.10,5.60),(.53,.53,2.20),BR,.008)
for i,z in enumerate([4.78,5.04,5.30,5.56,5.82,6.08,6.34]):box(f'Expert_ChimneyBand{i}',(1.38,1.10,z),(.55,.55,.025),BL,.001)
box('Expert_ChimneyCap',(1.38,1.10,6.74),(.72,.72,.18),T,.016); box('Expert_ChimneyHole',(1.38,1.10,6.84),(.35,.35,.12),bpy.data.materials.get('Dark'),.006)

# Rebuild the wraparound porch roof so it sits under the dormer instead of cutting into it.
slope_y('Expert_Porch_F',-3.02,-1.73,1.53,3.28,2.58,3.14,RB); tiles_y('ExpertPorchTF',-3.02,-1.73,1.53,3.28,2.58,3.14,5,9)
slope_x('Expert_Porch_S',3.30,1.70,-.30,3.58,2.62,3.14,RB); tiles_x('ExpertPorchTS',3.30,1.70,-.30,3.58,2.62,3.14,5,10)
slope_x('Expert_Entry_L',-.08,.52,-2.38,1.18,2.69,3.14,RB); slope_x('Expert_Entry_R',1.12,.52,-2.38,1.18,2.69,3.14,RB); tiles_x('ExpertEntryTL',-.08,.52,-2.38,1.18,2.69,3.14,3,4); tiles_x('ExpertEntryTR',1.12,.52,-2.38,1.18,2.69,3.14,3,4); box('Expert_Entry_Ridge',(.52,-2.38,3.19),(.14,1.28,.14),RT,.03)

# Reference-layout corrections preserved from the baseline.
# Bring the left tree forward so it is visible beside the facade like the source image.
for o in scene.objects:
    if o.name.startswith('TreeLeft'):
        o.location.y -= 1.35
# Lower front window has narrow brown side trim in the reference, not heavy shutters.
for nm in ('WinLower_SL','WinLower_SR'):
    o=bpy.data.objects.get(nm)
    if o:
        o.dimensions.x=.13; bpy.context.view_layer.objects.active=o; bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
# Slightly calm the grass saturation under the brighter studio setup.
set_base(bpy.data.materials.get('Grass'),(0.25,0.50,0.055),.90)

# Exact isometric camera matching the reference ground axes (+29/-33 deg).
def look(o,t):o.rotation_euler=(Vector(t)-o.location).to_track_quat('-Z','Y').to_euler()
for o in list(scene.objects):
    if o.type=='LIGHT':bpy.data.objects.remove(o,do_unlink=True)
scene.world.use_nodes=True;bg=scene.world.node_tree.nodes.get('Background');bg.inputs['Color'].default_value=(0.985,0.965,0.915,1);bg.inputs['Strength'].default_value=.40
try:scene.view_settings.view_transform='Standard';scene.view_settings.look='Medium High Contrast';scene.view_settings.exposure=0.0;scene.view_settings.gamma=1.0
except:pass

def area(n,loc,e,size,target,color):
    bpy.ops.object.light_add(type='AREA',location=loc);L=bpy.context.object;L.name=n;L.data.energy=e;L.data.shape='DISK';L.data.size=size;L.data.color=color;look(L,target)
area('Expert_Key',(-6.2,-7.0,11.5),820,6.2,(-.2,-.2,2.1),(1.0,.95,.86));area('Expert_Fill',(6.0,0.0,8.5),420,7.5,(0,0,2.2),(.92,.96,1.0));area('Expert_CameraFill',(7.5,-8.0,9.5),260,8.5,(0,-.2,2.3),(.96,.98,1.0));area('Expert_Front',(0,-8.0,6.0),160,8.0,(0,-.4,1.8),(1.0,.98,.94))
bpy.ops.object.light_add(type='SUN',location=(0,0,9));sun=bpy.context.object;sun.data.energy=.62;sun.data.angle=math.radians(18);sun.rotation_euler=(math.radians(30),math.radians(-16),math.radians(-35))
back=bpy.data.objects.get('Backdrop');
if back:
    back.dimensions=(30,30,.14); bpy.context.view_layer.objects.active=back; bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    if back.data.materials:set_base(back.data.materials[0],(0.985,0.955,0.885),.96)
cam=scene.camera
cam.data.type='ORTHO'
views={'preview_perspective.png':((10,-10,12),(0,-.05,2.0),9.65),'preview_front.png':((0,-14,5.2),(-.3,0,2.2),9.4),'preview_back.png':((0,14,5.2),(-.3,0,2.2),9.4),'preview_left.png':((-14,0,5.2),(0,0,2.2),9.4),'preview_right.png':((14,0,5.2),(0,0,2.2),9.4),'preview_top.png':((0,0,16),(0,0,0),9.6)}
for fn,(pos,target,scale) in views.items():cam.location=pos;cam.data.ortho_scale=scale;look(cam,target);scene.render.filepath=os.path.join(OUT,fn);bpy.ops.render.render(write_still=True)
# export refined GLB and save refined BLEND
for o in scene.objects:o.select_set(False)
for o in scene.objects:
    if o.type=='MESH' and o.name!='Backdrop':o.select_set(True)
bpy.ops.export_scene.gltf(filepath=os.path.join(OUT,'model.glb'),export_format='GLB',use_selection=True,export_apply=True)
cam.location=(10,-10,12);cam.data.ortho_scale=9.65;look(cam,(0,-.05,2.0));bpy.ops.wm.save_as_mainfile(filepath=os.path.join(OUT,'model.blend'))
print('EXPERT_REFINE_V8_COMPLETE')
